# Generated by Django 4.1.5 on 2023-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('fecha', models.CharField(max_length=200, verbose_name='fecha')),
                ('tipo', models.CharField(max_length=200, verbose_name='tipo')),
                ('descripción', models.CharField(max_length=200, null=True, verbose_name='descripcion')),
            ],
        ),
    ]
