# Generated by Django 4.1.5 on 2023-01-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendas',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
