# Generated by Django 4.1.5 on 2023-01-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='titulo')),
                ('categoria', models.CharField(max_length=200, verbose_name='categoria')),
                ('fecha', models.CharField(max_length=200, verbose_name='fecha')),
                ('descripción', models.CharField(max_length=200, verbose_name='descripcion')),
            ],
        ),
    ]
